version: '3'

services:
  vault:
    image: vault
    container_name: private_vault
    cap_add:
      - IPC_LOCK
    ports:
      - "127.0.0.1:8200:8200"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    volumes:
      - ./file:/vault/file:rw
      - ./config:/vault/config:rw
    entrypoint: vault server -config=/vault/config/vault.json
    networks:
      - ez_plattform

networks:
    ez_plattform:
        external:
            name: sf_ez_plattform